// packages/sinabeulo-react-docs/src/App.tsx
import React from 'react';
import { NavLink, Route, Switch } from 'react-router-dom';
import DocButton from './docs/Button.mdx';
import DocComponents from './docs/Components.mdx';
import DocIntroduction from './docs/Introduction.mdx';

function App(): JSX.Element {
  return (
    <div className="wrap">
      <div className="head">
        <h1>sinabeulo-react</h1>
      </div>
      <div className="headShadow" />
      <div className="side">
        <ul>
          <li>
            <NavLink to="/" exact>
              Introduction
            </NavLink>
          </li>
          <li>
            <NavLink to="/components" exact>
              Components
            </NavLink>
            <ul>
              <li>
                <NavLink to="/components/button" exact>
                  Button
                </NavLink>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <div className="main markdown-body">
        <Switch>
          <Route path="/" exact>
            <DocIntroduction />
          </Route>
          <Route path="/components" exact>
            <DocComponents />
          </Route>
          <Route path="/components/button" exact>
            <DocButton />
          </Route>
        </Switch>
      </div>
    </div>
  );
}

export default App;

// packages/sinabeulo-vue-docs/src/App.tsx
import { defineComponent } from 'vue';
import { RouterLink, RouterView } from 'vue-router';

const App = defineComponent({
  render() {
    return (
      <div class="wrap">
        <div class="head">
          <h1>sinabeulo-vue</h1>
        </div>
        <div class="headShadow" />
        <div class="side">
          <ul>
            <li>
              <RouterLink to="/">Introduction</RouterLink>
            </li>
            <li>
              <RouterLink to="/components">Components</RouterLink>
              <ul>
                <li>
                  <RouterLink to="/components/button">Button</RouterLink>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="main markdown-body">
          <RouterView />
        </div>
      </div>
    );
  },
});

export default App;
