// packages/sinabeulo-react/src/preview/CheckboxPreview.tsx
import React, { useCallback, useState } from 'react';
import { Checkbox } from '..';

export default function CheckboxPreview(props: {
  disabled: boolean;
}): JSX.Element {
  const { disabled } = props;
  const [isChecked, setIsChecked] = useState(false);
  const [isIndeterminate, setIsIndeterminate] = useState(true);
  const handleChange = useCallback(
    (_?: React.ChangeEvent<HTMLInputElement>, checked?: boolean) => {
      setIsChecked(!!checked);
      setIsIndeterminate(false);
    },
    []
  );

  return (
    <div
      style={{
        display: 'grid',
        gridAutoColumns: 'max-content',
        gridAutoRows: 'minmax(28px, auto)',
        gap: '10px',
        marginBottom: '10px',
      }}
    >
      <div style={{ gridRow: 1, gridColumn: 1 }}>
        <Checkbox disabled={disabled} label="Uncontrolled" />
      </div>
      <div style={{ gridRow: 1, gridColumn: 2 }}>
        <Checkbox disabled={disabled} label="Uncontrolled" defaultChecked />
      </div>
      <div style={{ gridRow: 1, gridColumn: 3 }}>
        <Checkbox
          disabled={disabled}
          label="Uncontrolled"
          defaultIndeterminate
        />
      </div>

      <div style={{ gridRow: 2, gridColumn: 1 }}>
        <Checkbox
          disabled={disabled}
          label="Controlled"
          checked={isChecked}
          onChange={handleChange}
        />
      </div>
      <div style={{ gridRow: 2, gridColumn: 2 }}>
        <Checkbox
          disabled={disabled}
          label="Controlled"
          checked={isChecked}
          onChange={handleChange}
        />
      </div>
      <div style={{ gridRow: 2, gridColumn: 3 }}>
        <Checkbox
          disabled={disabled}
          label="Controlled"
          checked={isChecked}
          indeterminate={isIndeterminate}
          onChange={handleChange}
        />
      </div>
    </div>
  );
}

// packages/sinabeulo-vue/src/preview/CheckboxPreview.tsx
import { defineComponent, ref, toRefs } from 'vue';
import { Checkbox } from '..';

export default defineComponent({
  components: { Checkbox },
  props: {
    disabled: {
      type: Boolean,
      required: false,
    },
  },
  setup(props) {
    const { disabled } = toRefs(props);
    const isChecked = ref(false);
    const isIndeterminate = ref(true);
    const handleChange = (_?: Event, checked?: boolean) => {
      isChecked.value = !!checked;
      isIndeterminate.value = false;
    };

    return () => (
      <div
        style={{
          display: 'grid',
          gridAutoColumns: 'max-content',
          gridAutoRows: 'minmax(28px, auto)',
          gap: '10px',
          marginBottom: '10px',
        }}
      >
        <div style={{ gridRow: 1, gridColumn: 1 }}>
          <Checkbox disabled={disabled.value} label="Uncontrolled" />
        </div>
        <div style={{ gridRow: 1, gridColumn: 2 }}>
          <Checkbox
            disabled={disabled.value}
            defaultChecked
            label="Uncontrolled"
          />
        </div>
        <div style={{ gridRow: 1, gridColumn: 3 }}>
          <Checkbox
            disabled={disabled.value}
            label="Uncontrolled"
            defaultIndeterminate
          />
        </div>

        <div style={{ gridRow: 2, gridColumn: 1 }}>
          <Checkbox
            disabled={disabled.value}
            label="Controlled"
            v-model:checked={isChecked.value}
          />
        </div>
        <div style={{ gridRow: 2, gridColumn: 2 }}>
          <Checkbox
            disabled={disabled.value}
            label="Controlled"
            checked={isChecked.value}
            onChange={handleChange}
          />
        </div>
        <div style={{ gridRow: 2, gridColumn: 3 }}>
          <Checkbox
            disabled={disabled.value}
            label="Controlled"
            checked={isChecked.value}
            indeterminate={isIndeterminate.value}
            onChange={handleChange}
          />
        </div>
      </div>
    );
  },
});
