// packages/sinabeulo-react/src/components/Button/Button.tsx
import React, {
  forwardRef,
  useCallback,
  useEffect,
  useMemo,
  useRef,
} from 'react';
import { ButtonClassNames, classNamesForButton } from '@sinabeulo/styles';
import { createClassName } from '@sinabeulo/utils';

/**
 * 버튼의 속성입니다.
 */
type ButtonProps = React.PropsWithChildren<{
  /**
   * 버튼의 CSS 클래스 이름입니다.
   */
  classNames?: Partial<ButtonClassNames>;
  /**
   * 버튼이 체크되어 있는지 여부입니다.
   */
  checked?: boolean;
  /**
   * 버튼이 비활성화되어 있는지 여부입니다.
   */
  disabled?: boolean;
  /**
   * 강조할 버튼인지 여부입니다.
   */
  primary?: boolean;
  /**
   * 버튼 클릭될 때의 콜백입니다.
   */
  onClick?: React.MouseEventHandler<HTMLButtonElement>;
}>;

/**
 * 버튼입니다.
 */
const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (props: ButtonProps, ref: React.ForwardedRef<HTMLButtonElement>) => {
    const {
      children,
      classNames,
      checked = false,
      disabled = false,
      primary = false,
      onClick,
    } = props;
    const refButton = useRef<HTMLButtonElement>(null);

    useEffect(() => {
      if (typeof ref === 'function') {
        ref(refButton.current);
      } else if (ref) {
        ref.current = refButton.current;
      }
    }, [ref]);

    const handleClick = useCallback(
      (event: React.MouseEvent<HTMLButtonElement>) => {
        if (disabled) {
          return;
        }
        onClick?.(event);
      },
      [disabled, onClick]
    );

    const cn = useMemo(() => classNamesForButton(classNames), [classNames]);
    return (
      <button
        type="button"
        ref={refButton}
        className={createClassName(primary ? cn.rootPrimary : cn.root, {
          [cn.checked]: checked,
        })}
        disabled={disabled}
        onClick={handleClick}
      >
        <span className={cn.container}>{children}</span>
      </button>
    );
  }
);
Button.defaultProps = {
  classNames: undefined,
  checked: undefined,
  disabled: undefined,
  primary: undefined,
  onClick: undefined,
};

export default Button;
export type { ButtonProps };

// packages/sinabeulo-vue/src/components/Button/Button.tsx
import { defineComponent, PropType } from 'vue';
import { ButtonClassNames, classNamesForButton } from '@sinabeulo/styles';
import { createClassName } from '@sinabeulo/utils';

/**
 * 버튼의 속성입니다.
 */
type ButtonProps = {
  /**
   * 버튼의 CSS 클래스 이름입니다.
   */
  classNames?: ButtonClassNames;
  /**
   * 버튼이 체크되어 있는지 여부입니다.
   */
  checked?: boolean;
  /**
   * 버튼이 비활성화되어 있는지 여부입니다.
   */
  disabled?: boolean;
  /**
   * 강조할 버튼인지 여부입니다.
   */
  primary?: boolean;
};

/**
 * 버튼입니다.
 */
const Button = defineComponent({
  name: 'Button',
  props: {
    classNames: {
      type: Object as PropType<Partial<ButtonClassNames>>,
      required: false,
      default: undefined,
    },
    checked: {
      type: Boolean,
      required: false,
    },
    disabled: {
      type: Boolean,
      required: false,
    },
    primary: {
      type: Boolean,
      required: false,
    },
  },
  emits: ['click'],
  computed: {
    cn() {
      return classNamesForButton(this.classNames);
    },
  },
  methods: {
    handleClick(event: MouseEvent) {
      if (this.disabled) {
        return;
      }
      this.$emit('click', event);
    },
  },
  render() {
    return (
      <button
        type="button"
        ref="refButton"
        class={createClassName(
          this.primary ? this.cn.rootPrimary : this.cn.root,
          {
            [this.cn.checked]: this.checked,
          }
        )}
        disabled={this.disabled}
        onClick={(event) => this.handleClick(event)}
      >
        <span class={this.cn.container}>{this.$slots.default?.()}</span>
      </button>
    );
  },
});

export default Button;
export type { ButtonProps };
