// packages/sinabeulo-svelte/src/components/Checkbox/Checkbox.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import {
    type CheckboxClassNames,
    classNamesForCheckbox,
  } from '@sinabeulo/styles';
  import { createClassName } from '@sinabeulo/utils';

  // eslint-disable-next-line no-undef, no-underscore-dangle
  if (!window.__SI_CHECKBOX_NO) {
    // eslint-disable-next-line no-undef, no-underscore-dangle
    window.__SI_CHECKBOX_NO = 1;
  }
  // eslint-disable-next-line no-undef, no-underscore-dangle, no-plusplus
  const inputId = `SiCheckbox-${window.__SI_CHECKBOX_NO++}`;
  const dispatch = createEventDispatcher();

  /**
   * 체크박스의 CSS 클래스 이름입니다.
   */
  export let classNames = undefined as Partial<CheckboxClassNames> | undefined;
  /**
   * 체크박스가 비활성화되어 있는지 여부입니다.
   */
  export let disabled = false;
  /**
   * 체크박스의 옆에 표시할 문자열입니다.
   */
  export let label = '';
  /**
   * 선택 여부입니다
   */
  export let checked = false;
  /**
   * 불확실한 상태로 표시할지 여부입니다.
   */
  export let indeterminate = false;

  $: cn = classNamesForCheckbox(classNames);

  function handleChange(e: Event) {
    if (disabled) {
      return;
    }
    checked = (e.target as HTMLInputElement).checked;
    indeterminate = false;
    dispatch('change', { origin: e, checked });
  }
</script>

<div
  class={createClassName(cn.root, {
    [cn.disabled]: !!disabled,
    [cn.checked]: !!checked && !indeterminate,
    [cn.indeterminate]: !!indeterminate,
  })}
>
  <input
    class={cn.input}
    type="checkbox"
    id={inputId}
    {disabled}
    {checked}
    on:change={handleChange}
  />
  <label class={cn.container} for={inputId}>
    {#if indeterminate}
      <span class={cn.icon}>&#xf0c8;</span>
    {:else}
      <span class={cn.icon}>&#xf00c;</span>
    {/if}
    <span class={cn.text}>{label}</span>
  </label>
</div>

// packages/sinabeulo-vue/src/components/Checkbox/Checkbox.tsx
import { computed, defineComponent, PropType, ref, toRefs } from 'vue';
import { CheckboxClassNames, classNamesForCheckbox } from '@sinabeulo/styles';
import { createClassName } from '@sinabeulo/utils';

let checkboxId = 1;

/**
 * 체크박스입니다.
 */
const Checkbox = defineComponent({
  name: 'SiCheckbox',
  props: {
    /**
     * 체크박스의 CSS 클래스 이름입니다.
     */
    classNames: {
      type: Object as PropType<Partial<CheckboxClassNames>>,
      required: false,
      default: undefined,
    },
    /**
     * 체크박스가 비활성화되어 있는지 여부입니다.
     */
    disabled: {
      type: Boolean,
      required: false,
      default: false,
    },
    /**
     * 체크박스의 옆에 표시할 문자열입니다.
     */
    label: {
      type: String,
      required: false,
      default: undefined,
    },
    /**
     * 선택 여부입니다. 제어 컴포넌트로 사용하려면 이 속성의 값을 지정해야 하고, 그렇지 않으면 비제어 컴포넌트로 사용됩니다.
     */
    checked: {
      type: Boolean,
      required: false,
      default: undefined,
    },
    /**
     * 제어 컴포넌트로 사용될 때 불확실한 상태로 표시할지 여부입니다.
     */
    indeterminate: {
      type: Boolean,
      required: false,
      default: undefined,
    },
    /**
     * 비제어 컴포넌트로 사용될 때 기본 체크 상태로 표시할지 여부입니다.
     */
    defaultChecked: {
      type: Boolean,
      required: false,
      default: undefined,
    },
    /**
     * 비제어 컴포넌트로 사용될 때 기본으로 불확실한 상태로 표시할지 여부입니다.
     */
    defaultIndeterminate: {
      type: Boolean,
      required: false,
      default: undefined,
    },
  },
  emits: ['change', 'update:checked'],
  setup(props, { emit }) {
    const {
      classNames,
      disabled,
      label,
      checked,
      indeterminate,
      defaultChecked,
      defaultIndeterminate,
    } = toRefs(props);
    const isControlled = checked.value !== undefined;
    const isCheckedIn = ref(defaultChecked.value);
    const isIndeterminateIn = ref(defaultIndeterminate.value);
    const isChecked = computed(() =>
      isControlled ? checked.value : isCheckedIn.value
    );
    const isIndeterminate = computed(() =>
      isControlled ? indeterminate.value : isIndeterminateIn.value
    );
    const handleChange = (e: Event) => {
      if (disabled.value) {
        return;
      }
      if (isControlled) {
        emit('change', e, (e.target as HTMLInputElement).checked);
        emit('update:checked', (e.target as HTMLInputElement).checked);
      } else {
        isCheckedIn.value = !isChecked.value;
        isIndeterminateIn.value = false;
      }
    };

    // eslint-disable-next-line no-plusplus
    const inputId = `SiCheckbox-${checkboxId++}`;
    const cn = classNamesForCheckbox(classNames.value);
    return () => (
      <div
        class={createClassName(cn.root, {
          [cn.disabled]: !!disabled.value,
          [cn.checked]: !!isChecked.value && !isIndeterminate.value,
          [cn.indeterminate]: !!isIndeterminate.value,
        })}
      >
        <input
          ref="refInput"
          class={cn.input}
          type="checkbox"
          id={inputId}
          disabled={disabled.value}
          checked={isChecked.value}
          onChange={handleChange}
        />
        <label class={cn.container} for={inputId}>
          {isIndeterminate.value ? (
            <span class={cn.icon}>&#xf0c8;</span>
          ) : (
            <span class={cn.icon}>&#xf00c;</span>
          )}
          <span class={cn.text}>{label.value}</span>
        </label>
      </div>
    );
  },
});

export default Checkbox;
