// packages/sinabeulo-react/src/preview/ButtonPreview.tsx
import React from 'react';
import { Button } from '..';

export default function ButtonPreview(props: {
  disabled: boolean;
}): JSX.Element {
  const { disabled } = props;
  return (
    <div
      style={{
        display: 'grid',
        gridAutoColumns: 'max-content',
        gridAutoRows: 'minmax(40px, auto)',
        gap: '10px',
        marginBottom: '10px',
      }}
    >
      <div style={{ gridRow: 1, gridColumn: 1 }}>
        <Button disabled={disabled}>Standard</Button>
      </div>
      <div style={{ gridRow: 1, gridColumn: 2 }}>
        <Button disabled={disabled} icon={<span>&#128513;</span>}>
          Standard
        </Button>
      </div>
      <div style={{ gridRow: 1, gridColumn: 3 }}>
        <Button disabled={disabled} icon={<span>&#128513;</span>} />
      </div>

      <div style={{ gridRow: 2, gridColumn: 1 }}>
        <Button disabled={disabled} primary>
          Primary
        </Button>
      </div>
      <div style={{ gridRow: 2, gridColumn: 2 }}>
        <Button disabled={disabled} primary icon={<span>&#128513;</span>}>
          Primary
        </Button>
      </div>
      <div style={{ gridRow: 2, gridColumn: 3 }}>
        <Button disabled={disabled} primary icon={<span>&#128513;</span>} />
      </div>

      <div style={{ gridRow: 3, gridColumn: 1 }}>
        <Button disabled={disabled} checked>
          Checked
        </Button>
      </div>
      <div style={{ gridRow: 3, gridColumn: 2 }}>
        <Button disabled={disabled} checked icon={<span>&#128513;</span>}>
          Checked
        </Button>
      </div>
      <div style={{ gridRow: 3, gridColumn: 3 }}>
        <Button disabled={disabled} checked icon={<span>&#128513;</span>} />
      </div>
    </div>
  );
}

// packages/sinabeulo-svelte/src/preview/ButtonPreview.svelte
<script lang="ts">
  import { Button } from '..';

  export let disabled = false;
</script>

<div
  style="display: grid; grid-auto-columns: max-content; grid-auto-rows: minmax(40px, auto); gap: 10px; margin-bottom: 10px;"
>
  <div style="grid-row: 1; grid-column: 1;">
    <Button {disabled}>Standard</Button>
  </div>
  <div style="grid-row: 1; grid-column: 2;">
    <Button {disabled}><span slot="icon">&#128513;</span>Standard</Button>
  </div>
  <div style="grid-row: 1; grid-column: 3;">
    <Button {disabled}><span slot="icon">&#128513;</span></Button>
  </div>

  <div style="grid-row: 2; grid-column: 1;">
    <Button {disabled} primary>Primary</Button>
  </div>
  <div style="grid-row: 2; grid-column: 2;">
    <Button {disabled} primary><span slot="icon">&#128513;</span>Primary</Button
    >
  </div>
  <div style="grid-row: 2; grid-column: 3;">
    <Button {disabled} primary><span slot="icon">&#128513;</span></Button>
  </div>

  <div style="grid-row: 3; grid-column: 1;">
    <Button {disabled} checked>Checked</Button>
  </div>
  <div style="grid-row: 3; grid-column: 2;">
    <Button {disabled} checked><span slot="icon">&#128513;</span>Checked</Button
    >
  </div>
  <div style="grid-row: 3; grid-column: 3;">
    <Button {disabled} checked><span slot="icon">&#128513;</span></Button>
  </div>
</div>
