// packages/sinabeulo-vue/src/preview/CheckboxPreview.tsx
import { defineComponent, ref, toRefs } from 'vue';
import { Checkbox } from '..';

export default defineComponent({
  components: { Checkbox },
  props: {
    disabled: {
      type: Boolean,
      required: false,
    },
  },
  setup(props) {
    const { disabled } = toRefs(props);
    const isChecked = ref(false);
    const isIndeterminate = ref(true);
    const handleChange = (_?: Event, checked?: boolean) => {
      isChecked.value = !!checked;
      isIndeterminate.value = false;
    };

    return () => (
      <div
        style={{
          display: 'grid',
          gridAutoColumns: 'max-content',
          gridAutoRows: 'minmax(28px, auto)',
          gap: '10px',
          marginBottom: '10px',
        }}
      >
        <div style={{ gridRow: 1, gridColumn: 1 }}>
          <Checkbox disabled={disabled.value} label="Uncontrolled" />
        </div>
        <div style={{ gridRow: 1, gridColumn: 2 }}>
          <Checkbox
            disabled={disabled.value}
            defaultChecked
            label="Uncontrolled"
          />
        </div>
        <div style={{ gridRow: 1, gridColumn: 3 }}>
          <Checkbox
            disabled={disabled.value}
            label="Uncontrolled"
            defaultIndeterminate
          />
        </div>

        <div style={{ gridRow: 2, gridColumn: 1 }}>
          <Checkbox
            disabled={disabled.value}
            label="Controlled"
            v-model:checked={isChecked.value}
          />
        </div>
        <div style={{ gridRow: 2, gridColumn: 2 }}>
          <Checkbox
            disabled={disabled.value}
            label="Controlled"
            checked={isChecked.value}
            onChange={handleChange}
          />
        </div>
        <div style={{ gridRow: 2, gridColumn: 3 }}>
          <Checkbox
            disabled={disabled.value}
            label="Controlled"
            checked={isChecked.value}
            indeterminate={isIndeterminate.value}
            onChange={handleChange}
          />
        </div>
      </div>
    );
  },
});

// packages/sinabeulo-svelte/src/preview/CheckboxPreview.svelte
<script lang="ts">
  import { Checkbox } from '..';

  export let disabled = false;

  let isChecked = false;
  let isIndeterminate = true;

  function handleChange(e: CustomEvent<{ e?: Event; checked?: boolean }>) {
    isChecked = !!e.detail.checked;
    isIndeterminate = false;
  }
</script>

<div>
  <div
    style="display: grid; grid-auto-columns: max-content; grid-auto-rows: minmax(28px, auto); gap: 10px; margin-bottom: 10px;"
  >
    <div style="grid-row: 1; grid-column: 1;">
      <Checkbox {disabled} label="Uncontrolled" />
    </div>
    <div style="grid-row: 1; grid-column: 2;">
      <Checkbox {disabled} label="Uncontrolled" checked />
    </div>
    <div style="grid-row: 1; grid-column: 3;">
      <Checkbox {disabled} label="Uncontrolled" indeterminate />
    </div>

    <div style="grid-row: 2; grid-column: 1;">
      <Checkbox {disabled} label="Controlled" bind:checked={isChecked} />
    </div>
    <div style="grid-row: 2; grid-column: 2;">
      <Checkbox
        {disabled}
        label="Controlled"
        checked={isChecked}
        on:change={handleChange}
      />
    </div>
    <div style="grid-row: 2; grid-column: 3;">
      <Checkbox
        {disabled}
        label="Controlled"
        checked={isChecked}
        indeterminate={isIndeterminate}
        on:change={handleChange}
      />
    </div>
  </div>
</div>
