// packages/sinabeulo-svelte/src/components/Radio/RadioGroup.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import {
    classNamesForRadioGroup,
    type RadioGroupClassNames,
  } from '@sinabeulo/styles';
  import Radio from './Radio.svelte';
  import type { RadioGroupItem } from './RadioGroupItem';

  const dispatch = createEventDispatcher();

  /**
   * 라디오 그룹의 CSS 클래스 이름입니다.
   */
  export let classNames = undefined as
    | Partial<RadioGroupClassNames>
    | undefined;
  /**
   * 라디오 그룹이 비활성화되어 있는지 여부입니다.
   */
  export let disabled = false;
  /**
   * 라디오 그룹 이름입니다.
   */
  export let name: string;
  /**
   * 라디오 그룹에 표시할 아이템 목록입니다.
   */
  export let items: RadioGroupItem[];
  /**
   * 라디오 그룹의 선택 값입니다.
   */
  export let selectedValue = undefined as string | number | undefined;

  $: cn = classNamesForRadioGroup(classNames);

  function handleCheck(e: CustomEvent<{ e?: Event; value?: string | number }>) {
    if (disabled) {
      return;
    }
    const item = items.find((i) => i.value === e.detail.value);
    selectedValue = item?.value;
    dispatch('change', { origin: e, item });
  }
</script>

<div class={cn.root}>
  {#each items as item}
    <Radio
      classNames={item.classNames}
      disabled={disabled || item.disabled}
      label={item.label}
      {name}
      value={item.value}
      checked={item.value === selectedValue}
      on:check={handleCheck}
    />
  {/each}
</div>

// packages/sinabeulo-vue/src/components/Radio/RadioGroup.tsx
import { defineComponent, PropType, toRefs } from 'vue';
import {
  RadioClassNames,
  RadioGroupClassNames,
  classNamesForRadioGroup,
} from '@sinabeulo/styles';
import Radio from './Radio';

/**
 * 라디오 그룹에 표시할 아이템의 속성입니다.
 */
type RadioGroupItem = {
  /**
   * 라디오의 CSS 클래스 이름입니다.
   */
  classNames?: RadioClassNames;
  /**
   * 라디오가 비활성화되어 있는지 여부입니다.
   */
  disabled?: boolean;
  /**
   * 라디오의 옆에 표시할 문자열입니다.
   */
  label?: string;
  /**
   * 라디오의 값입니다.
   */
  value?: string | number;
};

/**
 * 라디오입니다.
 */
const RadioGroup = defineComponent({
  name: 'SiRadioGroup',
  components: {
    Radio,
  },
  props: {
    /**
     * 라디오 그룹의 CSS 클래스 이름입니다.
     */
    classNames: {
      type: Object as PropType<Partial<RadioGroupClassNames>>,
      required: false,
      default: undefined,
    },
    /**
     * 라디오 그룹이 비활성화되어 있는지 여부입니다.
     */
    disabled: {
      type: Boolean,
      required: false,
      default: false,
    },
    /**
     * 라디오 그룹 이름입니다.
     */
    name: {
      type: String,
      required: true,
    },
    /**
     * 라디오 그룹에 표시할 아이템 목록입니다.
     */
    items: {
      type: Array as PropType<RadioGroupItem[]>,
      required: true,
      default: () => [],
    },
    /**
     * 라디오 그룹의 선택 값입니다.
     */
    selectedValue: {
      type: [String, Number] as PropType<string | number>,
      required: false,
      default: undefined,
    },
  },
  emits: ['change', 'update:selectedValue'],
  setup(props, { emit }) {
    const { classNames, disabled, name, items, selectedValue } = toRefs(props);
    const handleCheck = (e: Event, value?: string | number) => {
      if (disabled.value) {
        return;
      }
      const item = items.value.find((i) => i.value === value);
      emit('change', e, item);
      emit('update:selectedValue', item?.value);
    };

    const cn = classNamesForRadioGroup(classNames.value);
    return () => (
      <div class={cn.root}>
        {items.value.map((item) => (
          <Radio
            key={item.value}
            classNames={item.classNames}
            disabled={disabled.value || item.disabled}
            label={item.label}
            name={name.value}
            value={item.value}
            checked={item.value === selectedValue.value}
            onCheck={handleCheck}
          />
        ))}
      </div>
    );
  },
});

export default RadioGroup;
export type { RadioGroupItem };
