// packages/sinabeulo-react/src/components/Radio/Radio.tsx
import React, {
  forwardRef,
  useCallback,
  useEffect,
  useMemo,
  useRef,
} from 'react';
import { RadioClassNames, classNamesForRadio } from '@sinabeulo/styles';
import { createClassName } from '@sinabeulo/utils';
import useConst from '../../hooks/useConst';

/**
 * 라디오의 속성입니다.
 */
type RadioProps = {
  /**
   * CSS 클래스 이름입니다.
   */
  classNames?: Partial<RadioClassNames>;
  /**
   * 비활성화되어 있는지 여부입니다.
   */
  disabled?: boolean;
  /**
   * 옆에 표시할 문자열입니다.
   */
  label?: string;
  /**
   * 속하는 그룹 이름입니다.
   */
  name?: string;
  /**
   * 값입니다.
   */
  value?: string | number;
  /**
   * 선택 여부입니다.
   */
  checked?: boolean;
  /**
   * 선택할 때의 콜백입니다.
   */
  onCheck: (
    e?: React.ChangeEvent<HTMLInputElement>,
    value?: string | number
  ) => void;
};

let radioId = 1;

/**
 * 라디오입니다.
 */
const Radio = forwardRef<HTMLInputElement, RadioProps>(
  (props: RadioProps, ref: React.ForwardedRef<HTMLInputElement>) => {
    const { classNames, name, value, label, disabled, checked, onCheck } =
      props;
    const refInput = useRef<HTMLInputElement>(null);

    useEffect(() => {
      if (typeof ref === 'function') {
        ref(refInput.current);
      } else if (ref) {
        ref.current = refInput.current;
      }
    }, [ref]);

    const handleChange = useCallback(
      (e: React.ChangeEvent<HTMLInputElement>) => {
        if (disabled) {
          return;
        }
        onCheck?.(e, value);
      },
      [disabled, onCheck, value]
    );

    // eslint-disable-next-line no-plusplus
    const inputId = useConst(() => `SiRadio-${radioId++}`);
    const cn = useMemo(() => classNamesForRadio(classNames), [classNames]);
    return (
      <div
        className={createClassName(cn.root, {
          [cn.disabled]: !!disabled,
          [cn.checked]: !!checked,
        })}
      >
        <input
          ref={refInput}
          className={cn.input}
          type="radio"
          id={inputId}
          name={name}
          value={value}
          disabled={disabled}
          checked={checked}
          onChange={handleChange}
        />
        <label className={cn.container} htmlFor={inputId}>
          <span className={cn.icon}>&#xf111;</span>
          <span className={cn.text}>{label}</span>
        </label>
      </div>
    );
  }
);
Radio.defaultProps = {
  classNames: undefined,
  disabled: false,
  label: undefined,
  name: undefined,
  value: undefined,
  checked: false,
};

export default Radio;
export type { RadioProps };

// packages/sinabeulo-vue/src/components/Radio/Radio.tsx
import { defineComponent, PropType, toRefs } from 'vue';
import { RadioClassNames, classNamesForRadio } from '@sinabeulo/styles';
import { createClassName } from '@sinabeulo/utils';

let radioId = 1;

/**
 * 라디오입니다.
 */
const Radio = defineComponent({
  name: 'SiRadio',
  props: {
    /**
     * 라디오의 CSS 클래스 이름입니다.
     */
    classNames: {
      type: Object as PropType<Partial<RadioClassNames>>,
      required: false,
      default: undefined,
    },
    /**
     * 라디오가 비활성화되어 있는지 여부입니다.
     */
    disabled: {
      type: Boolean,
      required: false,
      default: false,
    },
    /**
     * 라디오의 옆에 표시할 문자열입니다.
     */
    label: {
      type: String,
      required: false,
      default: undefined,
    },
    /**
     * 라디오가 속하는 그룹 이름입니다.
     */
    name: {
      type: String,
      required: false,
      default: undefined,
    },
    /**
     * 라디오의 값입니다.
     */
    value: {
      type: [String, Number] as PropType<string | number>,
      required: false,
      default: undefined,
    },
    /**
     * 선택 여부입니다.
     */
    checked: {
      type: Boolean,
      required: false,
      default: false,
    },
  },
  emits: ['check'],
  setup(props, { emit }) {
    const { classNames, disabled, label, name, value, checked } = toRefs(props);
    const handleChange = (e: Event) => {
      if (disabled.value) {
        return;
      }
      emit('check', e, value.value);
    };

    // eslint-disable-next-line no-plusplus
    const inputId = `SiRadio-${radioId++}`;
    const cn = classNamesForRadio(classNames.value);
    return () => (
      <div
        class={createClassName(cn.root, {
          [cn.disabled]: !!disabled.value,
          [cn.checked]: !!checked.value,
        })}
      >
        <input
          ref="refInput"
          class={cn.input}
          type="radio"
          id={inputId}
          name={name.value}
          value={value.value}
          disabled={disabled.value}
          checked={checked.value}
          onChange={handleChange}
        />
        <label class={cn.container} for={inputId}>
          <span class={cn.icon}>&#xf111;</span>
          <span class={cn.text}>{label.value}</span>
        </label>
      </div>
    );
  },
});

export default Radio;
