// packages/sinabeulo-react-docs/src/components/Flex.tsx
import React from 'react';

type FlexProps = React.PropsWithChildren<{
  direction?: 'horizontal' | 'vertical';
  gap?: number;
}>;

const Flex = (props: FlexProps): JSX.Element => {
  const { children, direction = 'horizontal', gap = 4 } = props;
  return (
    <div
      style={{
        alignItems: 'center',
        display: 'flex',
        flexDirection: direction === 'horizontal' ? 'row' : 'column',
        gap: `${gap}px`,
      }}
    >
      {children}
    </div>
  );
};
Flex.defaultProps = {
  direction: 'horizontal',
  gap: 4,
};

export default Flex;
export type { FlexProps };

// packages/sinabeulo-vue-docs/src/components/Flex.tsx
import { defineComponent, PropType } from 'vue';

interface FlexProps {
  direction?: 'horizontal' | 'vertical';
  gap?: number;
}

const Flex = defineComponent({
  props: {
    direction: {
      type: String as PropType<'horizontal' | 'vertical'>,
      requried: false,
      default: 'horizontal',
    },
    gap: {
      type: Number,
      required: false,
      default: 4,
    },
  },
  render() {
    return (
      <div
        style={{
          alignItems: 'center',
          display: 'flex',
          flexDirection: this.direction === 'horizontal' ? 'row' : 'column',
          gap: `${this.gap}px`,
        }}
      >
        {this.$slots.default?.()}
      </div>
    );
  },
});

export default Flex;
export type { FlexProps };
